### ISSUE TITLE
Great component! Is the source for decTreeViewDll.32.dll provided?

### ISSUE THREAD

**Issue by edwinyzh** [DenisAnisimov/decTreeView#1]
I discovered this component, and it's amazing, thanks!
Is the decTreeViewDll.32.dll source code commercial or do you have a plan to open source it? Thanks.

**Comment by DenisAnisimov** [comment]
Why do you need decTreeViewDll.32.dll source code? If you are Delphi developer you can use component directly without any additional dll.

**Comment by edwinyzh** [comment]
I'm really sorry! I browsed the code and thought the Delphi code **relies on** the dll files. I'
I'm sorry. I'll close this issue.
