### ISSUE TITLE
Wrap text

### ISSUE THREAD

**Issue by marcelosehnem** [DenisAnisimov/decTreeView#3]
Hello, how did you do to wrap the text in the node?

**Comment by DenisAnisimov** [comment]
Don't understand the question. Please more clarify.

**Comment by marcelosehnem** [comment]
In the readme example, there are nodes with 1 row, 2 rows and 3 rows. How do I add more than one row to a node?

**Comment by DenisAnisimov** [comment]
Caption := 'Line1' + sLineBreak + 'Line2' + sLineBreak + 'Line3'

**Comment by marcelosehnem** [comment]
It worked! thanks!
