### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by delphi-coder** [DenisAnisimov/decTreeView#4]
I Simply put the component on the form and got the exception RangeCheck Error on runtime.
Using Delphi 11

**Comment by DenisAnisimov** [comment]
Windows version?

**Comment by DenisAnisimov** [comment]
The compiler of Delphi11 is oversmart. It doesn't like the integer->dword conversions when the integer is less than zero. I fixed two places I found, there may be more. But it's easier to disable the check in the compiler options.
